name: WorldLoader
version: 1.0
main: WorldLoader\Main
author: Kyd7
api: [3.0.0-ALPHA3, 3.0.0-ALPHA4]
description: Plugin that load worlds in PocketMine

commands:
   load:
     description: Load world command
     usage: /load [world]
   loadall:
     description: Load all worlds on server
     usage: /loadall
